# Generated by Django 4.0.1 on 2022-01-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'پیک', 'verbose_name_plural': 'پیک ها'},
        ),
    ]
