# Generated by Django 4.0.1 on 2022-02-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_addrese'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='addrese',
            new_name='address',
        ),
    ]
