# Generated by Django 4.0.1 on 2022-01-28 12:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.CharField(max_length=120, verbose_name='اسم مغازه')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره همراه')),
                ('shop_phone', models.CharField(max_length=20, verbose_name='شماره ثابت')),
                ('work_time', models.CharField(max_length=200, verbose_name='ساعت کاری')),
                ('morning_work', models.BooleanField(default=True, verbose_name='کار صبح')),
            ],
            options={
                'verbose_name': 'نانوایی',
                'verbose_name_plural': 'نانوایی ها',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
