# Generated by Django 4.0.1 on 2022-01-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_bakery_bread_type_bakery_order_count_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bakery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakery.bakery', verbose_name='نانوا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('انتظار تایید پیک', 'انتظار تایید پیک'), ('تو راهم', 'تو راهم'), ('رسید دستش', 'رسید دستش')], default=('انتظار تایید پیک', 'انتظار تایید پیک'), max_length=30, verbose_name='وضعیت'),
        ),
    ]
