# Generated by Django 4.0.1 on 2022-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_bakery_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('انتظار تایید پیک', 'انتظار تایید پیک'), ('تو راهم', 'تو راهم'), ('رسید دستش', 'رسید دستش')], max_length=30, verbose_name='وضعیت'),
        ),
    ]
